### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by sebastianzillessen** [8zrealestate/flurry-phonegap-plugin#4]
Hello, 

I'm just wondering under which Licence this plugin is published... Can it be used in other projects?

Thanks!

**Comment by 8zrealestate** [comment]
Good question.  I filed an issue with the original author: https://github.com/jfpsf/flurry-phonegap-plugin/issues/8 and will use a compatible license.

**Comment by mooreds** [comment]
It is licensed under Apache 2.0.  I updated the readme to reflect this.  Thanks for the question!
